services:
  dev:
    build: .
    volumes:
      - type: bind
        source: .
        target: /mnt/blog
    working_dir: /mnt/blog
    network_mode: host
    stdin_open: true
    tty: true
    command: /bin/bash

  serve:
    build: .
    volumes:
      - type: bind
        source: ./blog
        target: /mnt/blog
    working_dir: /mnt/blog
    network_mode: host
    command: >
      /bin/bash -c "npm install -g npm@latest
      && npm install
      && npm run dev
      "
